### ISSUE TITLE
Sending emails fails (1.2.8)

### ISSUE THREAD

**Issue by alex-vy** [EaDesgin/magento2-pdf-generator2#83]
Magento Version 2.3.1
Extension Version:  1.2.8

When I try to send any email with this module on I always get PHP errors (even if I disable the extension on Admin panel). PDFs print out fine,

This is the error I get:
```
2019/05/04  [error] 17887#17887: *878 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function setFrom() on null in /usr/share/www/1234/vendor/magento/framework/Mail/Message.php:111
Stack trace:
#0 /usr/share/www/1234/generated/code/Eadesigndev/Pdfgenerator/Model/Email/Message/Interceptor.php(206): Magento\Framework\Mail\Message->setFromAddress('sales@smth....', 'smth')
#1 /usr/share/www/1234/vendor/magento/framework/Mail/Template/TransportBuilder.php(206): Eadesigndev\Pdfgenerator\Model\Email\Message\Interceptor->setFromAddress('sales@smth....', 'smth')
#2 /usr/share/www/1234/generated/code/Eadesigndev/Pdfgenerator/Model/Email/TransportBuilder/Interceptor.php(102): Magento\Framework\Mail\Template\TransportBuilder->setFromByScope('sales', '2')
#3 /usr/share/www/1234/vendor/magento/module-sales/Model/Order/Email/SenderBuilder.php(111): Eadesigndev\Pdfgenerator\Model\Email\TransportBuilder\Interceptor->setFromByScope('sales', '2')
#4 /usr/share/www/1234/vendor/magento/module-sales/Model/Or" while reading response header from upstream, client: 127.0.0.1, server: local.magento, request: "GET /admin/sales/order/email/order_id/126/key/7b40f53c312739805dfebae8053c822c39325d98ca79797f3db7f44998c22cf5/ HTTP/1.1", upstream: "fastcgi://unix:/run/php72-fpm/php-fpm.sock:", host: "local.magento", referrer: "http://local.magento/admin/sales/order/view/order_id/126/key/6bcf0882c1fd484f7b78806c4a6dc547fe399986e4b1fdbb651ab02ea58e22ef/"
```
Is this some sort of permission issue? What's causing this?

**Comment by alex-vy** [comment]
By changing:
magento/vendor/eadesignro/module-pdfgenerator/Model/Email/Message.php
from:
```
    public function setFrom($fromAddress)
    {
        $this->zendMessage->setFrom($fromAddress);
        return $this;
    }
```
To:

```
    public function setFromAddress($fromAddress, $fromName = null)
    {
        $this->zendMessage->setFrom($fromAddress, $fromName);
        return $this;
    }
```
I am able to send the email, but they are blank.

**Comment by alex-vy** [comment]
#82 Pull request fixes the issue.

Are you still maintaining this free extension?

**Comment by eadesignro** [comment]
This should be fixed in the new release. Let me know it there are other issues. Thanks for the help and sorry for the late response.
